### ISSUE TITLE
Emailing cloudbrain

### ISSUE THREAD

**Issue by bdyetton** [cloudbrain/cloudbrain#13]
Hi Cloudbrain team. I just tried to send an email to this email address: hello@cloudbrainlabs.com which I got from the cloudbrain website (the email was just to say hello and ask more about what you do). Unfortunately I got this reply, and figured you might want to know.

> This is an automatically generated Delivery Status Notification
> 
> THIS IS A WARNING MESSAGE ONLY.
> 
> YOU DO NOT NEED TO RESEND YOUR MESSAGE.
> 
> Delivery to the following recipient has been delayed:
> 
>      hello@cloudbrainlabs.com
> 
> Message will be retried for 1 more day(s)
> 
> Technical details of temporary failure:
> DNS Error: 11459112 DNS type 'mx' lookup of cloudbrainlabs.com responded with code SERVFAIL

**Comment by jnaulty** [comment]
Hey @bdyetton 
You should checkout [getcloudbrain.com](http://getcloudbrain.com/) as well as [neurotechx.com](http://neurotechx.com/) . It will give you a better idea of what we do, what our goals are, and who we are. 
The [README.md](https://github.com/cloudbrain/cloudbrain/blob/master/README.md) has general and specific information regarding what the cloudbrain project is trying to achieve. And the brief description `Open-source platform for wearable analytics.` Is also a pretty good summary.

**Comment by bdyetton** [comment]
Thanks. Ill clone and have a play when I get time. Any plans to support the lab streaming layer? https://github.com/sccn/labstreaminglayer

**Comment by marionleborgne** [comment]
Hey @bdyetton. Thanks for catching that. The website email is fixed.

Regarding LSL, it's not in our short term plan. What is your use case? How would you like to use LSL with cloudbrain?

Thanks!

**Comment by baffo32** [comment]
> Regarding LSL, it's not in our short term plan. What is your use case? How would you like to use LSL with cloudbrain?

LSL is supported by most EEG devices already, supports also synchronized video, audio, and events, and streams it all between arbitrary nodes on a network.  Its only big drawback is no associated database storage.  Is cloudbrain redoing this work that it's not using LSL?

Code allowing interoperability between cloudbrain and LSL would allow support for many new devices, but anybody could write this plugin.

On the other hand, integrating LSL may significantly reduce duplicated development and maintenance effort between the projects.

https://github.com/sccn/labstreaminglayer

**Comment by marionleborgne** [comment]
Closing issue since LSL is in our list of TODOs. Just not the highest priority for now. Thanks for the feedback @baffo32
